/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardUserRouteImport } from './routes/_dashboard/user'
import { Route as DashboardMaintenanceRouteImport } from './routes/_dashboard/maintenance'
import { Route as DashboardIncidentRouteImport } from './routes/_dashboard/incident'
import { Route as DashboardElevatorRouteImport } from './routes/_dashboard/elevator'
import { Route as DashboardContractRouteImport } from './routes/_dashboard/contract'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardElevatorElevatorIdRouteImport } from './routes/_dashboard/elevator.$elevatorId'
import { Route as DashboardContractContractIdRouteImport } from './routes/_dashboard/contract.$contractId'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUserRoute = DashboardUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMaintenanceRoute = DashboardMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardIncidentRoute = DashboardIncidentRouteImport.update({
  id: '/incident',
  path: '/incident',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardElevatorRoute = DashboardElevatorRouteImport.update({
  id: '/elevator',
  path: '/elevator',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContractRoute = DashboardContractRouteImport.update({
  id: '/contract',
  path: '/contract',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardElevatorElevatorIdRoute =
  DashboardElevatorElevatorIdRouteImport.update({
    id: '/$elevatorId',
    path: '/$elevatorId',
    getParentRoute: () => DashboardElevatorRoute,
  } as any)
const DashboardContractContractIdRoute =
  DashboardContractContractIdRouteImport.update({
    id: '/$contractId',
    path: '/$contractId',
    getParentRoute: () => DashboardContractRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/contract': typeof DashboardContractRouteWithChildren
  '/elevator': typeof DashboardElevatorRouteWithChildren
  '/incident': typeof DashboardIncidentRoute
  '/maintenance': typeof DashboardMaintenanceRoute
  '/user': typeof DashboardUserRoute
  '/contract/$contractId': typeof DashboardContractContractIdRoute
  '/elevator/$elevatorId': typeof DashboardElevatorElevatorIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/contract': typeof DashboardContractRouteWithChildren
  '/elevator': typeof DashboardElevatorRouteWithChildren
  '/incident': typeof DashboardIncidentRoute
  '/maintenance': typeof DashboardMaintenanceRoute
  '/user': typeof DashboardUserRoute
  '/': typeof DashboardIndexRoute
  '/contract/$contractId': typeof DashboardContractContractIdRoute
  '/elevator/$elevatorId': typeof DashboardElevatorElevatorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_dashboard/contract': typeof DashboardContractRouteWithChildren
  '/_dashboard/elevator': typeof DashboardElevatorRouteWithChildren
  '/_dashboard/incident': typeof DashboardIncidentRoute
  '/_dashboard/maintenance': typeof DashboardMaintenanceRoute
  '/_dashboard/user': typeof DashboardUserRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/contract/$contractId': typeof DashboardContractContractIdRoute
  '/_dashboard/elevator/$elevatorId': typeof DashboardElevatorElevatorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/contract'
    | '/elevator'
    | '/incident'
    | '/maintenance'
    | '/user'
    | '/contract/$contractId'
    | '/elevator/$elevatorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/contract'
    | '/elevator'
    | '/incident'
    | '/maintenance'
    | '/user'
    | '/'
    | '/contract/$contractId'
    | '/elevator/$elevatorId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_auth/login'
    | '/_dashboard/contract'
    | '/_dashboard/elevator'
    | '/_dashboard/incident'
    | '/_dashboard/maintenance'
    | '/_dashboard/user'
    | '/_dashboard/'
    | '/_dashboard/contract/$contractId'
    | '/_dashboard/elevator/$elevatorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/user': {
      id: '/_dashboard/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof DashboardUserRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/maintenance': {
      id: '/_dashboard/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof DashboardMaintenanceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/incident': {
      id: '/_dashboard/incident'
      path: '/incident'
      fullPath: '/incident'
      preLoaderRoute: typeof DashboardIncidentRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/elevator': {
      id: '/_dashboard/elevator'
      path: '/elevator'
      fullPath: '/elevator'
      preLoaderRoute: typeof DashboardElevatorRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/contract': {
      id: '/_dashboard/contract'
      path: '/contract'
      fullPath: '/contract'
      preLoaderRoute: typeof DashboardContractRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/elevator/$elevatorId': {
      id: '/_dashboard/elevator/$elevatorId'
      path: '/$elevatorId'
      fullPath: '/elevator/$elevatorId'
      preLoaderRoute: typeof DashboardElevatorElevatorIdRouteImport
      parentRoute: typeof DashboardElevatorRoute
    }
    '/_dashboard/contract/$contractId': {
      id: '/_dashboard/contract/$contractId'
      path: '/$contractId'
      fullPath: '/contract/$contractId'
      preLoaderRoute: typeof DashboardContractContractIdRouteImport
      parentRoute: typeof DashboardContractRoute
    }
  }
}

interface DashboardContractRouteChildren {
  DashboardContractContractIdRoute: typeof DashboardContractContractIdRoute
}

const DashboardContractRouteChildren: DashboardContractRouteChildren = {
  DashboardContractContractIdRoute: DashboardContractContractIdRoute,
}

const DashboardContractRouteWithChildren =
  DashboardContractRoute._addFileChildren(DashboardContractRouteChildren)

interface DashboardElevatorRouteChildren {
  DashboardElevatorElevatorIdRoute: typeof DashboardElevatorElevatorIdRoute
}

const DashboardElevatorRouteChildren: DashboardElevatorRouteChildren = {
  DashboardElevatorElevatorIdRoute: DashboardElevatorElevatorIdRoute,
}

const DashboardElevatorRouteWithChildren =
  DashboardElevatorRoute._addFileChildren(DashboardElevatorRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardContractRoute: typeof DashboardContractRouteWithChildren
  DashboardElevatorRoute: typeof DashboardElevatorRouteWithChildren
  DashboardIncidentRoute: typeof DashboardIncidentRoute
  DashboardMaintenanceRoute: typeof DashboardMaintenanceRoute
  DashboardUserRoute: typeof DashboardUserRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardContractRoute: DashboardContractRouteWithChildren,
  DashboardElevatorRoute: DashboardElevatorRouteWithChildren,
  DashboardIncidentRoute: DashboardIncidentRoute,
  DashboardMaintenanceRoute: DashboardMaintenanceRoute,
  DashboardUserRoute: DashboardUserRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
